"""Generated credentials the model asks for but never sees.

The model writes {{DBA_SECRET:mysql_root}} where a password belongs. The harness
swaps in a strong generated value on the way to the server and swaps it back out
of anything on the way to the model, the transcript, or the report. So a weak
password is not something the model can choose, and a real one is not something
it can leak into its own context.

The values also stay on the servers they belong to, because the next run needs
them. A task is rarely the first one these machines have had, and the password a
run has to log in with is the one an earlier run set: without it the model has no
way in and no way to work one out. What that looks like is on record - a migration
run opened with `mysql` and no password, hunted through /etc, the error log and
root's shell history for a credential the harness had never written there, and
finally reset the root password through skip-grant-tables. Ninety-one steps, and
the operator's note of the old password was silently wrong afterwards.

So each server keeps every credential in a root-only file that later runs read
back, and a follow-up task needs no flag and nothing looked up by hand. The file
lives in /etc/profile.d, so the values are also in the environment of every command
the harness runs and of anyone who logs in - `mysql -p"$DBA_SECRET_MYSQL_ROOT"`
works by hand, and the model can write the variable instead of a placeholder.

That is a deliberate trade. The plaintext now sits on the machine it belongs to,
where a snapshot, a backup or a compromise of that machine exposes it; root there
could already read the data these passwords protect, which is why it is a
reasonable one, and --no-server-secrets keeps them in the run directory only.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import shlex
import stat
from pathlib import Path

PLACEHOLDER = re.compile(r"\{\{DBA_SECRET:([A-Za-z0-9_.-]{1,64})\}\}")
# url-safe alphabet: no quotes, backslashes or spaces to survive a shell round trip
_BYTES = 18

ENV_PREFIX = "DBA_SECRET_"
# /etc/profile.d, because every command already goes through `bash -lc` (see
# ssh.wrap_command), which sources it. So no wrapper change is needed for the
# values to be in every step's environment, an operator on the box has them too,
# and the same file is what the next run reads its names and values back out of.
#
# Not /etc/environment: PAM reads that for every user and it is world-readable by
# convention, which is the one thing this file must not be.
KEEPER_PATH = "/etc/profile.d/dba-secrets.sh"
KEEPER_MODE = "0600"
KEEPER_HEADER = [
    "# Credentials generated by do-dba for this server. Root only.",
    "# Sourced by every login shell, so `mysql -p\"$DBA_SECRET_MYSQL_ROOT\"` works here.",
    "# Later runs read this file: it is how they know what already works on this server.",
    "# Delete a line to make the next run generate a new value for that name.",
]

_UNSAFE = re.compile(r"[^a-z0-9]+")


def canonical(name: str) -> str:
    """The one spelling of a credential's name.

    Case and punctuation are not a distinction worth keeping. Two runs asking for
    MYSQL_ROOT_PASSWORD and mysql_root_password mean the same password, and minting
    a second value for the second spelling is how a run locks itself out of the
    server the last one configured - which is exactly what happened.
    """
    cleaned = _UNSAFE.sub("_", (name or "").strip().lower()).strip("_")
    return cleaned or "secret"


def env_name(name: str) -> str:
    """The environment variable a credential is exported as."""
    return ENV_PREFIX + canonical(name).upper()


class SecretStore:
    def __init__(self) -> None:
        self._values: dict[str, str] = {}
        # Which came off a server rather than being generated here: the model is
        # told these already work, so it uses them instead of resetting them.
        self._inherited: set[str] = set()
        # A value exists that no server has been told about yet. Pushed as soon as
        # it is used, not at the end: a run that dies mid-way has still changed a
        # password, and a password nobody can look up is the failure this avoids.
        self._unsaved = False

    @property
    def names(self) -> list[str]:
        return sorted(self._values)

    @property
    def inherited(self) -> list[str]:
        """The credentials that were already in place when this run started."""
        return sorted(self._inherited)

    @property
    def unsaved(self) -> bool:
        return self._unsaved

    def resolve(self, text: str) -> str:
        """Replace every placeholder with its value, generating on first use."""
        return PLACEHOLDER.sub(lambda match: self._value(match.group(1)), text)

    def redact(self, text: str) -> str:
        """Put the placeholders back, so no real value is shown or stored."""
        if not text:
            return text
        for name, value in self._values.items():
            if value and value in text:
                text = text.replace(value, f"{{{{DBA_SECRET:{name}}}}}")
        return text

    def _value(self, name: str) -> str:
        key = canonical(name)
        if key not in self._values:
            self._values[key] = secrets.token_urlsafe(_BYTES)
            self._unsaved = True
        return self._values[key]

    def adopt(self, values: dict[str, str]) -> tuple[list[str], list[str]]:
        """Take in the credentials a server already holds.

        Returns the names learned and the names that clashed - a server whose value
        for a name differs from one already read off another. The first value read
        wins, because changing it under a step that has already run is worse, and
        the clash is reported rather than resolved: two machines that disagree about
        a shared password is a fact about the fleet, not a thing to paper over.
        """
        learned, clashed = [], []
        for name, value in values.items():
            key = canonical(name)
            if not value:
                continue
            if key in self._values:
                if self._values[key] != value:
                    clashed.append(key)
                continue
            self._values[key] = value
            self._inherited.add(key)
            learned.append(key)
        return sorted(learned), sorted(clashed)

    def env_script(self) -> str:
        """The file the servers keep: exports, quoted so any value survives."""
        lines = list(KEEPER_HEADER)
        lines += [f"export {env_name(name)}={shlex.quote(self._values[name])}"
                  for name in self.names]
        return "\n".join(lines) + "\n"

    def mark_saved(self) -> None:
        self._unsaved = False

    def save(self, path: Path) -> Path | None:
        """Write the credentials out, readable only by the current user."""
        if not self._values:
            return None
        path.parent.mkdir(parents=True, exist_ok=True)
        # Created at 0600 by os.open, not opened under the umask's permissions and
        # narrowed afterwards: between those two moments the file holds every
        # credential in the clear at whatever the umask allowed. (Windows ACLs do
        # not map onto POSIX modes; the CRT applies what it can of the mode, and a
        # missing mapping is the same best effort the chmod here used to be.)
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC,
                             stat.S_IRUSR | stat.S_IWUSR)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(self._values, handle, indent=2, sort_keys=True)
        return path


def parse_keeper(text: str) -> dict[str, str]:
    """Read the exports back out of a keeper file, ignoring anything else in it.

    shlex, not a regex: the values are shell-quoted on the way out, and an operator
    may have edited the file by hand.
    """
    found: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("export ") or "=" not in stripped:
            continue
        try:
            tokens = shlex.split(stripped[len("export "):])
        except ValueError:
            continue  # an unbalanced quote: skip the line rather than the file
        for token in tokens:
            variable, _, value = token.partition("=")
            if variable.startswith(ENV_PREFIX) and value:
                found[canonical(variable[len(ENV_PREFIX):])] = value
    return found


def read_keeper(runner, path: str = KEEPER_PATH) -> dict[str, str]:
    """What this server already holds, or nothing if it holds nothing readable.

    Silent about failure on purpose: no file is the normal case on a machine this
    harness has not touched, and an unreadable one means the account is not root,
    which the run reports on its own.
    """
    try:
        result = runner.run(f"cat {shlex.quote(path)} 2>/dev/null", timeout=30)
    except Exception:
        return {}
    return parse_keeper(result.stdout or "")


def write_keeper(runner, store: SecretStore, path: str = KEEPER_PATH) -> str:
    """Put every credential on the server. Returns "" or why it could not.

    Every credential rather than the ones this server used: which machine needs
    which is not knowable here - a replication password belongs on both ends - and
    a value missing from the one server that needed it is the whole problem.
    """
    if not store.names:
        return ""
    try:
        result = runner.write_file(path, store.env_script(), mode=KEEPER_MODE)
    except Exception as exc:  # a bookkeeping write must never sink a finished run
        return str(exc)[:160]
    if getattr(result, "ok", True):
        return ""
    said = (getattr(result, "stderr", "") or getattr(result, "stdout", "") or "").strip()
    return (said or "the write failed")[:160]
